package it.polimi.ingsw.GC_26_player;

import it.polimi.ingsw.GC_26_utilities.resourcesAndPoints.ResourcesOrPoints;
import it.polimi.ingsw.GC_26_utilities.resourcesAndPoints.Warehouse;


import it.polimi.ingsw.GC_26_cards.developmentCards.DevelopmentCard;
import it.polimi.ingsw.GC_26_gameLogic.Action;
import it.polimi.ingsw.GC_26_personalBoard.PersonalBoard;
import it.polimi.ingsw.GC_26_serverView.Observable;
import it.polimi.ingsw.GC_26_utilities.Message;
import it.polimi.ingsw.GC_26_utilities.Request;
import it.polimi.ingsw.GC_26_utilities.familyMembers.FamilyMembers;

public class Player extends Observable<Message> {
	private final String name;
	private final Warehouse warehouse;
	private final PermanentModifiers permanentModifiers;
	private final FamilyMembers familyMembers;
	private PlayerStatus status;
	
	//previous status is used to keep memory of status; 
		//It' s needed in case of interruptions.
	private PlayerStatus previousStatus;  
	
	private Warehouse testWarehouse;
	//temporaryWarehouse is used in some calculations:
	// 1) checking if the player can pay something 
	// 2) in Production or Harvest we must ensure the player is not using resources just earned in trading, so we take an image of resources before action

	private final PersonalBoard personalBoard;
	private boolean playerActive; //set true if the player has at least tried to perform an action during the round.
	// reached when a player has not performed an action 	
	
	
	// pointer to the card used when the player is asked something, such as choosing payment or trade
	private DevelopmentCard cardUsed;
	
	// parameters set and used if a second action(the actions that are generated by cards effects) occurs
	private boolean secondaryAction=false;
	private ResourcesOrPoints discountOnSecondAction; 
	private Action typeOfSecondaryAction;
	private int secondActionValue;
	
	public Player(String name, ResourcesOrPoints startingResources) {
		this.name=name;
		status= PlayerStatus.WAITINGHISTURN;
		personalBoard= new PersonalBoard();
		permanentModifiers = new PermanentModifiers(this);
		familyMembers = new FamilyMembers(this);
		playerActive= false;
		warehouse= new Warehouse(this, startingResources);
		}


	
	
	//getters methods
	public String getName() {
		return this.name;
	}
	
	public FamilyMembers getFamilyMembers() {
		return familyMembers;
	}
	
	public PersonalBoard getPersonalBoard() {
		return personalBoard;
	}
	public Warehouse getWarehouse() {
		return warehouse;
	}
	
	public Warehouse getTestWarehouse() {
		return testWarehouse;
	}
	
	public PermanentModifiers getPermanentModifiers() {
		return permanentModifiers;
	}
	
	public PlayerStatus getStatus(){
		return status;
	}
	
	public PlayerStatus getPreviousStatus() {
		return previousStatus;
	}
	public boolean isPlayerActive() {
		return playerActive;
	}
	
	
	
	//setters methods
	
	public void setStatus(Request request){
		PlayerStatus temp = request.getStatus();
		if(temp!= this.status)
			previousStatus= this.status;
		this.status = temp;
		if(temp!=PlayerStatus.SUSPENDED)
			notifyObservers(request);
		
	}
	
	
	public void backToPreviousStatus() {
		status=previousStatus;
	}
	
	public void setTemporaryWarehouse(){
		testWarehouse = new Warehouse(warehouse);
		
	}
	
	public void setPlayerActive() {
		this.playerActive = true;
	}
	
	public void endTurn(){
		playerActive=false;
	}
	
	public boolean isThereAsecondaryAction(){
		return secondaryAction;
	}
	public void setSecondaryAction(){
		secondaryAction = true;
	}
	public void setDiscountOnSecondAction(ResourcesOrPoints discountOnSecondAction) {
		this.discountOnSecondAction = discountOnSecondAction;
	}
	public ResourcesOrPoints getDiscountOnSecondAction() {
		return discountOnSecondAction;
	}
	public void setTypeOfSecondaryAction(Action typeOfSecondaryAction) {
		this.typeOfSecondaryAction = typeOfSecondaryAction;
	}
	public Action getTypeOfSecondaryAction() {
		return typeOfSecondaryAction;
	}
	public int getSecondactionValue() {
		return secondActionValue;
	}
	public void setSecondactionValue(int secondactionValue) {
		this.secondActionValue = secondactionValue;
	}
	
	public void resetSecondAction(){
		secondaryAction=false;
		discountOnSecondAction=null;
		typeOfSecondaryAction=null;
		secondActionValue=0;
	}
	
	public DevelopmentCard getCardUsed() {
		return cardUsed;
	}
	
	public void setCardUsed(DevelopmentCard cardUsed) {
		this.cardUsed = cardUsed;
	}
	

	

}
